import Link from 'next/link';
import { ChevronRight } from 'lucide-react';
import { ContentHero } from '@/components/content/Editorial';
import { KnowledgeActions } from '@/components/member/KnowledgeActions';
import type { PublishedContent } from '@/lib/repository';
import { mapJourneyPortal, type PortalStage } from './journey-portal-mapper';
import { JourneyBlockRenderer } from './blocks/JourneyBlockRenderer';
import { JourneyReadingProgress } from './JourneyReadingProgress';
import { deriveJourneyNavigation } from './journey-navigation';
import { BackToTop, JourneyReaderLayout, SectionNavigator } from './JourneyNavigator';

function StageContent({ stage, stages, slug, paymentType }: { stage: PortalStage; stages: PortalStage[]; slug: string; paymentType: string }) {
  const index=stages.findIndex((item)=>item.id===stage.id),adjacent=(offset:number)=>stages[index+offset];
  const sections=stage.states.map((state)=>({id:state.id,title:state.title}));
  return <section id="journey-stage-content" className="min-w-0 max-w-full scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-4 sm:p-6">
    <p className="text-xs font-semibold uppercase tracking-wide text-royalBlue">Stage {index+1} of {stages.length}</p>
    <h2 className="mt-2 break-words text-2xl font-semibold text-navy sm:text-3xl">{stage.title}</h2>
    {stage.summary?<p className="mt-3 max-w-3xl text-textSecondary">{stage.summary}</p>:null}
    <SectionNavigator sections={sections}/>
    {stage.states.length?<div className="mt-5 grid min-w-0 max-w-full grid-cols-[minmax(0,1fr)] gap-5">{stage.states.map((state)=><article key={state.id} id={`state-${state.id}`} style={{scrollMarginTop:'9rem'}} className="min-w-0 max-w-full overflow-hidden border-t border-slate-200 pt-4"><h3 className="max-w-3xl font-semibold text-navy">{state.title}</h3>{state.summary?<p className="mt-2 max-w-3xl text-sm leading-6 text-textSecondary">{state.summary}</p>:null}<div className="mt-3 min-w-0 max-w-full space-y-3">{state.blocks.map((block)=><JourneyBlockRenderer key={block.id} block={block}/>)}</div></article>)}</div>:<p className="mt-6 rounded-xl border border-dashed border-slate-300 p-5 text-sm text-textSecondary">No documentation is available for this stage yet.</p>}
    <div className="mt-7 flex flex-wrap justify-between gap-3 border-t border-slate-200 pt-5">{adjacent(-1)?<Link href={`/${slug}?paymentType=${paymentType}&stage=${adjacent(-1)!.id}`} className="min-h-11 font-semibold text-royalBlue">← Previous: {adjacent(-1)!.title}</Link>:<span/>}{adjacent(1)?<Link href={`/${slug}?paymentType=${paymentType}&stage=${adjacent(1)!.id}`} className="min-h-11 font-semibold text-royalBlue">Next: {adjacent(1)!.title} →</Link>:null}</div>
  </section>;
}

function PaymentTypeCards({content,model}:{content:PublishedContent;model:ReturnType<typeof mapJourneyPortal>}){return <section id="payment-types" className="mt-8"><h2 className="text-3xl font-semibold text-navy">Payment Types</h2><div className="mt-5 space-y-6">{model.paymentTypeGroups.map((group)=><div key={group.id}><h3 className="font-semibold text-navy">{group.title}</h3><div className="mt-3 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{group.paymentTypes.map((payment)=><Link key={payment.id} href={`/banking-journeys/${content.slug}?paymentType=${payment.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:border-royalBlue hover:shadow-md focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-royalBlue"><span className="inline-flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-sm font-bold text-royalBlue">{payment.title.slice(0,1)}</span><h4 className="mt-4 font-semibold text-navy">{payment.title}</h4><p className="mt-2 text-sm leading-6 text-textSecondary">{payment.summary}</p><p className="mt-3 text-xs text-slate-500">{payment.stageCount} lifecycle stages · {payment.knowledgeNodeCount} knowledge sections</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-royalBlue">Open Journey <ChevronRight aria-hidden="true" className="h-4 w-4 transition-transform group-hover:translate-x-0.5"/></span></Link>)}</div></div>)}</div></section>}

function LegacyPublishedContent({content,model,selectedId}:{content:PublishedContent;model:ReturnType<typeof mapJourneyPortal>;selectedId?:string}){const selected=model.legacyModules.find((item)=>item.id===selectedId)??model.legacyModules[0];return <section className="mt-8"><div className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><h2 className="text-xl font-semibold text-navy">Detailed Payment Type journeys are being prepared.</h2><p className="mt-2 text-sm leading-6 text-textSecondary">Explore the currently published Payments &amp; Transfers knowledge below.</p></div>{selected?<div className="mt-6 grid gap-6 lg:grid-cols-[260px_minmax(0,1fr)] lg:items-start"><nav aria-label="Published Payments and Transfers modules" className="space-y-2 lg:sticky lg:top-24">{model.legacyModules.map((item)=><Link key={item.id} href={`/banking-journeys/${content.slug}?module=${item.id}`} aria-current={item.id===selected.id?'page':undefined} className={`block rounded-xl border p-3 text-sm font-semibold ${item.id===selected.id?'border-royalBlue bg-blue-50 text-royalBlue':'border-slate-200 bg-white text-navy'}`}>{item.title}</Link>)}</nav><article className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-wide text-royalBlue">Published knowledge module</p><h2 className="mt-2 text-3xl font-semibold text-navy">{selected.title}</h2><div className="mt-6 space-y-8">{selected.sections.map((section)=><section key={section.id} id={`section-${section.id}`} className="scroll-mt-24"><h3 className="text-xl font-semibold text-navy">{section.title}</h3><div className="mt-4 space-y-4">{section.blocks.map((block)=><JourneyBlockRenderer key={block.id} block={block}/>)}</div></section>)}</div></article></div>:<p className="mt-6 rounded-xl border border-dashed border-slate-300 p-5 text-sm text-textSecondary">No published Payments &amp; Transfers knowledge is available yet.</p>}</section>}

export function PaymentsJourneyPortal({content,paymentType,stage,module}:{content:PublishedContent;paymentType?:string;stage?:string;module?:string}){
  const model=mapJourneyPortal(content),payments=model.paymentTypeGroups.flatMap((group)=>group.paymentTypes),selected=payments.find((payment)=>payment.slug===paymentType),selectedStage=selected?.lifecycle.find((item)=>item.id===stage)||selected?.lifecycle[0];
  return <><JourneyReadingProgress/><ContentHero eyebrow="Banking Journey" title={content.title} summary={content.summary} parentLabel="Banking Journeys" parentHref="/banking-journeys"/><section className="min-w-0 overflow-hidden px-4 py-6 sm:px-6 sm:py-8 lg:px-8 lg:py-12"><div className="mx-auto min-w-0 max-w-7xl"><KnowledgeActions type={content.type} slug={content.slug}/>{model.mode==='LEGACY_PUBLISHED_CONTENT'?<LegacyPublishedContent content={content} model={model} selectedId={module}/>:!selected?<><section id="overview" className="mt-8"><p className="max-w-3xl leading-7 text-textSecondary">Select a Payment Type to explore its payment-specific lifecycle and stage documentation.</p></section><PaymentTypeCards content={content} model={model}/></>:<section className="mt-5 min-w-0"><Link href={`/banking-journeys/${content.slug}#payment-types`} className="inline-flex min-h-11 items-center text-sm font-semibold text-royalBlue">← Back to Payment Types</Link><p className="mt-5 text-xs font-semibold uppercase tracking-wide text-royalBlue">Selected Payment Type</p><h1 className="mt-2 break-words text-3xl font-semibold text-navy">{selected.title}</h1><p className="mt-3 max-w-prose break-words leading-7 text-textSecondary">{selected.summary}</p><div className="mt-5"><JourneyReaderLayout stages={deriveJourneyNavigation(selected.lifecycle)} slug={`banking-journeys/${content.slug}`} paymentType={selected.slug} selectedStage={selectedStage?.id??''}>{selectedStage?<StageContent stage={selectedStage} stages={selected.lifecycle} slug={`banking-journeys/${content.slug}`} paymentType={selected.slug}/>:<p className="rounded-xl border border-dashed p-5 text-textSecondary">No lifecycle stage content is available yet.</p>}{model.relatedJourneys.length?<section className="mt-10"><h2 className="text-2xl font-semibold text-navy">Related Knowledge</h2><div className="mt-4 flex flex-wrap gap-3">{model.relatedJourneys.map((related)=><Link key={related} href={`/banking-journeys/${related}`} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-royalBlue hover:border-royalBlue">{related.replaceAll('-', ' ')} →</Link>)}</div></section>:null}</JourneyReaderLayout></div></section>}</div></section><BackToTop/></>;
}
