import Link from 'next/link'; import { LockKeyhole, Search, ShieldCheck } from 'lucide-react';
import { Navbar } from '@/components/layout/Navbar'; import { Footer } from '@/components/layout/Footer'; import { db } from '@/lib/db';
import { getCurrentLocale } from '@/i18n/server'; import { getDictionary } from '@/i18n/get-dictionary';
import { formatCurrency } from '@/i18n/format';
export async function LandingPage(){const locale=await getCurrentLocale(),d=getDictionary(locale),l=d.landing;const[counts,plans]=await Promise.all([db.contentItem.groupBy({by:['type'],where:{isArchived:false,publishedRevisionId:{not:null}},_count:true}),db.membershipPlan.findMany({where:{isActive:true,isPublic:true},orderBy:{displayOrder:'asc'},select:{id:true,name:true,description:true,price:true,currency:true,billingPeriod:true,durationDays:true,featuresJson:true,translations:{where:{locale},take:1,select:{name:true,description:true,featuresJson:true}}}})]);const total=counts.reduce((s,x)=>s+x._count,0);return <><Navbar/><main>
<section id="overview" className="bg-navy px-4 py-20 text-white sm:px-6 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="text-sm font-semibold text-goldLight">{l.eyebrow}</p><h1 className="mt-5 max-w-4xl text-4xl font-semibold tracking-tight sm:text-6xl">{l.headline}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">{l.supporting}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={`/${locale}/request-access`} className="inline-flex min-h-12 items-center rounded-xl bg-royalBlue px-6 font-semibold">{l.primary}</Link><Link href={`/${locale}/login`} className="inline-flex min-h-12 items-center rounded-xl border border-white/25 px-6 font-semibold">{l.secondary}</Link></div><p className="mt-5 text-sm text-slate-400">{l.trust}</p></div><div className="rounded-[28px] border border-white/15 bg-white/5 p-5"><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="font-semibold">{l.workspace}</span><span className="inline-flex items-center gap-2 rounded-full bg-goldAccent/15 px-3 py-1 text-xs text-goldLight"><LockKeyhole className="h-4 w-4"/>{l.membersOnly}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{l.previews.map(x=><div key={x} className="rounded-2xl border border-white/10 bg-navyLight p-5"><p className="text-sm font-semibold">{x}</p><div className="mt-4 h-2 w-3/4 rounded bg-white/15"/></div>)}</div><div className="mt-3 flex min-h-14 items-center gap-3 rounded-2xl border border-white/10 px-4 text-sm text-slate-300"><Search className="h-5 w-5"/>{l.memberSearch}</div></div></div></section>
<section id="membership-preview" className="px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><p className="text-sm font-semibold text-royalBlue">{l.previewEyebrow}</p><h2 className="mt-3 text-3xl font-semibold text-navy sm:text-4xl">{l.previewTitle}</h2><p className="mt-4 max-w-3xl leading-7 text-textSecondary">{l.previewCopy}</p><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{l.pillars.map(([title,copy])=><article key={title} className="rounded-2xl border border-slate-200 bg-white p-6"><LockKeyhole className="h-5 w-5 text-goldAccent"/><h3 className="mt-4 text-xl font-semibold text-navy">{title}</h3><p className="mt-3 text-sm leading-6 text-textSecondary">{copy}</p><Link href={`/${locale}/request-access`} className="mt-5 inline-flex font-semibold text-royalBlue">{l.requestAccess}</Link></article>)}</div></div></section>
<section id="methodology" className="bg-white px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-semibold text-navy">{l.methodTitle}</h2><div className="mt-10 grid gap-4 md:grid-cols-4">{l.methods.map(([x,y],i)=><div key={x} className="rounded-2xl bg-bgLight p-6"><span className="text-sm font-semibold text-goldAccent">0{i+1}</span><h3 className="mt-3 text-xl font-semibold">{x}</h3><p className="mt-2 text-sm leading-6 text-textSecondary">{y}</p></div>)}</div><p className="mt-8 text-sm text-textSecondary">{total?l.count(total):l.countFallback}</p></div></section>
<section className="px-4 py-20 sm:px-6"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><h2 className="text-3xl font-semibold text-navy">{l.outcomesTitle}</h2><ul className="mt-6 grid gap-3 text-textSecondary">{l.outcomes.map(x=><li key={x} className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-royalBlue"/>{x}</li>)}</ul></div><div><h2 className="text-3xl font-semibold text-navy">{l.processTitle}</h2><ol className="mt-6 space-y-4">{l.process.map((x,i)=><li key={x} className="flex items-center gap-4 rounded-xl bg-white p-4"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-navy font-semibold text-white">{i+1}</span><span className="font-semibold">{x}</span></li>)}</ol></div></div></section>
<section id="membership" className="bg-navy px-4 py-20 text-white sm:px-6"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-semibold">{l.membershipTitle}</h2><div className="mt-8 grid gap-5 lg:grid-cols-2">{plans.length?plans.map(p=><article key={p.id} className="rounded-2xl border border-white/15 bg-white/5 p-7"><h3 className="text-2xl font-semibold">{p.translations[0]?.name??p.name}</h3><p className="mt-3 text-slate-300">{p.translations[0]?.description??p.description}</p><p className="mt-5 text-3xl font-semibold">{formatCurrency(p.price,p.currency,locale)}</p><Link href={`/${locale}/request-access?plan=${p.id}`} className="mt-6 inline-flex min-h-12 items-center rounded-xl bg-royalBlue px-5 font-semibold">{l.requestMembership}</Link></article>):<div className="rounded-2xl border border-white/15 p-7"><h3 className="text-2xl font-semibold">{l.noPlanTitle}</h3><p className="mt-3 text-slate-300">{l.noPlan}</p><Link href={`/${locale}/request-access`} className="mt-6 inline-flex min-h-12 items-center rounded-xl bg-royalBlue px-5 font-semibold">{l.requestMembership}</Link></div>}</div></div></section>
<section id="faq" className="px-4 py-20 sm:px-6"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-semibold text-navy">{l.faqTitle}</h2><div className="mt-8 space-y-3">{l.faqs.map(([q,a])=><details key={q} className="rounded-xl border border-slate-200 bg-white p-5"><summary className="min-h-11 cursor-pointer font-semibold">{q}</summary><p className="pt-2 leading-7 text-textSecondary">{a}</p></details>)}</div></div></section>
<section className="bg-goldPale px-4 py-16 text-center"><h2 className="text-3xl font-semibold text-navy">{l.finalTitle}</h2><p className="mx-auto mt-3 max-w-2xl text-textSecondary">{l.finalCopy}</p><Link href={`/${locale}/request-access`} className="mt-6 inline-flex min-h-12 items-center rounded-xl bg-navy px-6 font-semibold text-white">{l.primary}</Link></section>
</main><Footer/></>}
