import type { JourneyBlockViewModel } from './journey-block-types';
import { BusinessProcessDiagram, isBusinessProcessDiagram } from './BusinessProcessDiagram';

type PortalBlock = JourneyBlockViewModel;

const record = (value: unknown) => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
const display = (value: unknown) => typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean' ? String(value) : JSON.stringify(value);
const listDisplay = (value: unknown) => { if (!value || typeof value !== 'object' || Array.isArray(value)) return display(value); const item = value as Record<string, unknown>; if (typeof item.name === 'string') return item.description ? `${item.name}: ${item.description}` : item.name; return typeof item.label === 'string' ? item.label : JSON.stringify(value); };
const values = (value: unknown) => Array.isArray(value) ? value : [];

function TextBlock({ payload }: { payload: Record<string, unknown> }) { const value = payload.text ?? payload.content ?? payload.description ?? payload.value; return typeof value === 'string' && value.trim() ? <p className="max-w-prose break-words whitespace-pre-wrap text-sm leading-7 text-textSecondary">{value}</p> : null; }
function ListBlock({ payload }: { payload: Record<string, unknown> }) { const items = values(payload.items ?? payload.values ?? payload.list).filter((item) => item !== null && item !== undefined); return items.length ? <ul className="list-disc space-y-2 pl-5 text-sm leading-6 text-textSecondary">{items.map((item, index) => <li key={index}>{listDisplay(item)}</li>)}</ul> : null; }
function TableBlock({ payload }: { payload: Record<string, unknown> }) { const rows = values(payload.rows); const headers = values(payload.headers ?? payload.columns); return <div className="max-w-full overflow-x-auto rounded-lg" aria-label={typeof payload.title === 'string' ? payload.title : 'Content table'}><table className="min-w-[28rem] w-full border-collapse text-left text-sm sm:min-w-[32rem]"><caption className="sr-only">{typeof payload.title === 'string' ? payload.title : 'Content table'}</caption>{headers.length ? <thead><tr>{headers.map((header, index) => <th key={index} scope="col" className="break-words border-b border-slate-200 bg-slate-50 px-2 py-2 font-semibold text-navy sm:px-3">{display(header)}</th>)}</tr></thead> : null}<tbody>{rows.map((row, rowIndex) => <tr key={rowIndex}>{(Array.isArray(row) ? row : Object.values(record(row))).map((cell, cellIndex) => <td key={cellIndex} className="break-words border-b border-slate-100 px-2 py-2 align-top text-textSecondary sm:px-3">{display(cell)}</td>)}</tr>)}</tbody></table></div>; }
function ApiBlock({ payload }: { payload: Record<string, unknown> }) { const method = typeof payload.method === 'string' ? payload.method : 'API'; const endpoint = payload.endpoint ?? payload.path; const known = new Set(['method', 'endpoint', 'path', 'service', 'purpose', 'request', 'requestBody', 'response', 'responseBody', 'errors', 'statusCodes']); return <div className="min-w-0 max-w-full space-y-4"><div className="flex flex-wrap items-center gap-3"><span className="rounded-md bg-navy px-2 py-1 text-xs font-bold text-white">{method}</span>{endpoint ? <code className="break-all text-sm text-royalBlue">{display(endpoint)}</code> : null}</div>{['service', 'purpose'].map((key) => typeof payload[key] === 'string' ? <p key={key} className="text-sm text-textSecondary"><span className="font-semibold text-navy">{key === 'service' ? 'Service' : 'Purpose'}: </span>{payload[key] as string}</p> : null)}{[['Request', payload.request ?? payload.requestBody], ['Response', payload.response ?? payload.responseBody], ['Errors / Status', payload.errors ?? payload.statusCodes]].map(([label, value]) => value !== undefined ? <section key={label as string}><h4 className="font-semibold text-navy">{label as string}</h4><pre className="mt-2 max-w-full overflow-x-auto rounded-lg bg-slate-950 p-3 text-xs leading-5 text-slate-100">{typeof value === 'string' ? value : JSON.stringify(value, null, 2)}</pre></section> : null)}{Object.entries(payload).filter(([key]) => !known.has(key)).length ? <details><summary className="cursor-pointer text-sm font-semibold text-royalBlue">Additional details</summary><pre className="mt-2 overflow-x-auto text-xs">{JSON.stringify(Object.fromEntries(Object.entries(payload).filter(([key]) => !known.has(key))), null, 2)}</pre></details> : null}</div>; }
function DiagramBlock({ payload, allowBusinessProcess = false }: { payload: Record<string, unknown>; allowBusinessProcess?: boolean }) { if (allowBusinessProcess && isBusinessProcessDiagram(payload)) return <BusinessProcessDiagram payload={payload} />; const steps = values(payload.steps ?? payload.nodes); const source = payload.source ?? payload.mermaid ?? payload.plantuml; return steps.length ? <ol className="min-w-0 max-w-full flex flex-wrap items-center gap-2 text-sm">{steps.map((step, index) => <li key={index} className="rounded-lg border border-slate-200 px-3 py-2 text-navy">{display(step)}{index < steps.length - 1 ? <span className="ml-2 text-royalBlue">→</span> : null}</li>)}</ol> : <><h4 className="font-semibold text-navy">Diagram source</h4><pre className="mt-2 max-w-full overflow-x-auto rounded-lg bg-slate-950 p-3 text-xs text-slate-100">{display(source ?? payload)}</pre></>; }
function UnknownBlock({ block }: { block: PortalBlock }) { return <details><summary className="cursor-pointer text-sm font-semibold text-royalBlue">Unsupported block: {block.blockType}</summary><pre className="mt-2 max-h-72 overflow-auto rounded-lg bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(block.payload, null, 2)}</pre></details>; }

export function JourneyBlockRenderer({ block }: { block: PortalBlock }) { const payload = record(block.payload); const type = block.blockType.toUpperCase(); const content = type === 'TABLE' ? <TableBlock payload={payload} /> : ['API_REFERENCE', 'API', 'ENDPOINT', 'REQUEST_RESPONSE'].includes(type) ? <ApiBlock payload={payload} /> : type === 'DIAGRAM' ? <DiagramBlock payload={payload} allowBusinessProcess /> : ['FLOW', 'SEQUENCE'].includes(type) ? <DiagramBlock payload={payload} /> : ['CHECKLIST', 'LIST', 'BULLET_LIST', 'ORDERED_LIST'].includes(type) ? <ListBlock payload={payload} /> : ['RICH_TEXT', 'TEXT', 'PARAGRAPH', 'CALLOUT', 'CODE'].includes(type) ? <TextBlock payload={payload} /> : <UnknownBlock block={block} />; return <div className="min-w-0 max-w-full overflow-hidden rounded-xl border border-slate-200 bg-white p-3 sm:p-4">{type === 'CALLOUT' ? <p className="font-semibold text-navy">{typeof payload.title === 'string' ? payload.title : 'Note'}</p> : null}{content}</div>; }
