'use client';
import { useActionState } from 'react'; import { submitAccessRequestAction,type AccessRequestFormState } from '@/app/membership-actions';
const initial:AccessRequestFormState={ok:false};
export function AccessRequestForm({plans,selectedPlan,locale}:{plans:{id:string;name:string}[];selectedPlan?:string;locale:'en'|'vi'}){const[state,action,pending]=useActionState(submitAccessRequestAction,initial),v=locale==='vi';if(state.ok)return <div role="status" className="rounded-2xl border border-green-200 bg-green-50 p-6 text-green-900"><h2 className="text-xl font-semibold">{v?'Đã nhận yêu cầu':'Request received'}</h2><p className="mt-2 leading-7">{v?'Yêu cầu của bạn đã được ghi nhận. Quyền truy cập chỉ được cấp sau khi quản trị viên phê duyệt, xác nhận thanh toán và kích hoạt tài khoản.':state.message}</p></div>;const error=(name:string)=>state.errors?.[name]?.[0];return <form action={action} className="space-y-5" noValidate><input type="hidden" name="preferredLocale" value={locale}/>{state.message?<p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-800">{v?'Vui lòng kiểm tra lại thông tin.':state.message}</p>:null}
<Field name="name" label={v?'Họ và tên':'Full name'} error={error('name')}/><Field name="email" label="Email" type="email" error={error('email')}/><Field name="organization" label={v?'Tổ chức hoặc công ty (không bắt buộc)':'Organization or company (optional)'} optional error={error('organization')}/><Field name="jobTitle" label={v?'Vai trò nghề nghiệp':'Job title or professional role'} error={error('jobTitle')}/><Field name="currentBALevel" label={v?'Cấp độ BA hiện tại (không bắt buộc)':'Current BA level (optional)'} optional error={error('currentBALevel')}/><Field name="primaryInterest" label={v?'Lĩnh vực quan tâm chính':'Main area of interest'} error={error('primaryInterest')}/>
<label className="block text-sm font-semibold">{v?'Gói thành viên':'Requested membership plan'}<select name="requestedPlanId" defaultValue={selectedPlan??''} className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-3 font-normal"><option value="">{v?'Trao đổi với quản trị viên':'To be discussed'}</option>{plans.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
<label className="block text-sm font-semibold">{v?'Mục tiêu nghề nghiệp':'Short professional objective'}<textarea name="professionalObjective" required minLength={20} maxLength={700} rows={5} className="mt-2 w-full rounded-xl border border-slate-300 p-3 font-normal"/>{error('professionalObjective')?<span className="mt-1 block text-sm text-red-700">{error('professionalObjective')}</span>:null}</label>
<label className="flex gap-3 text-sm leading-6"><input required name="consentAccepted" type="checkbox" className="mt-1 h-5 w-5"/><span>{v?'Tôi đồng ý để nền tảng sử dụng thông tin này nhằm xem xét và liên hệ về gói thành viên. Việc gửi yêu cầu không tự động tạo tài khoản hoặc cấp quyền truy cập.':'I consent to the use of these details to review and contact me about membership. Submitting does not create an account or grant access.'}</span></label>
<button disabled={pending} className="min-h-12 w-full rounded-xl bg-royalBlue px-5 font-semibold text-white disabled:opacity-60">{pending?(v?'Đang gửi…':'Submitting…'):(v?'Gửi yêu cầu truy cập':'Submit Access Request')}</button></form>}
function Field({name,label,type='text',error,optional=false}:{name:string;label:string;type?:string;error?:string;optional?:boolean}){return <label className="block text-sm font-semibold">{label}<input name={name} type={type} required={!optional} aria-invalid={Boolean(error)} className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-3 font-normal"/>{error?<span className="mt-1 block text-sm text-red-700">{error}</span>:null}</label>}
