import Link from 'next/link';
import { assignKnowledgePackageAction, manageKnowledgeScopeGrantAction, revokeKnowledgeScopeGrantAction } from '@/app/actions';
import { WorkspaceTitle } from '@/components/workspace/WorkspaceShell';
import { db } from '@/lib/db';
import { requireRole } from '@/lib/auth';

export const dynamic = 'force-dynamic'; export const revalidate = 0;
export default async function AccessControlPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  await requireRole('ADMIN'); const { q } = await searchParams;
  const [users, scopes, packages, grants, audit] = await Promise.all([
    db.user.findMany({ where: q ? { OR: [{ name: { contains: q } }, { email: { contains: q } }] } : {}, select: { id: true, name: true, email: true, role: true }, orderBy: { name: 'asc' }, take: 100 }),
    db.knowledgeScope.findMany({ where: { isActive: true }, select: { id: true, code: true, nameEn: true }, orderBy: { displayOrder: 'asc' } }),
    db.knowledgePackage.findMany({ where: { isActive: true }, select: { id: true, nameEn: true, descriptionEn: true }, orderBy: { displayOrder: 'asc' } }),
    db.userScopeGrant.findMany({ where: { status: 'ACTIVE' }, include: { user: { select: { name: true, email: true } }, knowledgeScope: { select: { nameEn: true } } }, orderBy: { updatedAt: 'desc' }, take: 100 }),
    db.auditLog.findMany({ where: { action: { startsWith: 'KNOWLEDGE_' } }, include: { actor: { select: { name: true } } }, orderBy: { createdAt: 'desc' }, take: 25 }),
  ]);
  return <><WorkspaceTitle eyebrow="Administration" title="Knowledge Access Matrix" description="Scope grants are evaluated server-side before any premium content is queried. Every change is auditable." />
    <form className="mb-5 flex gap-2"><input name="q" defaultValue={q} placeholder="Find user" className="min-h-11 rounded-xl border border-slate-300 px-3" /><button className="rounded-xl bg-navy px-4 font-semibold text-white">Search</button></form>
    <form action={manageKnowledgeScopeGrantAction} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-semibold">User<select required name="userId" className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-2"><option value="">Select user</option>{users.map((user) => <option value={user.id} key={user.id}>{user.name} · {user.email}</option>)}</select></label><label className="text-sm font-semibold">Knowledge scope<select required name="knowledgeScopeId" className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-2"><option value="">Select scope</option>{scopes.map((scope) => <option value={scope.id} key={scope.id}>{scope.nameEn}</option>)}</select></label><label className="text-sm font-semibold">Permission<select name="permission" className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-2">{['VIEW','CREATE','EDIT','REVIEW','PUBLISH','MANAGE'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-semibold">Effect<select name="effect" className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-2"><option>ALLOW</option><option>DENY</option></select></label><label className="text-sm font-semibold">Expires (optional)<input name="expiresAt" type="datetime-local" className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-2" /></label><label className="text-sm font-semibold sm:col-span-2">Reason<input name="reason" maxLength={500} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-2" /></label><button className="min-h-11 rounded-xl bg-royalBlue px-4 font-semibold text-white">Grant or update</button></form>
    <form action={assignKnowledgePackageAction} className="mt-5 grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-[1fr_1fr_1fr_auto]"><label className="text-sm font-semibold">Role template / package<select required name="packageId" className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-2"><option value="">Select package</option>{packages.map((item) => <option value={item.id} key={item.id}>{item.nameEn}</option>)}</select></label><label className="text-sm font-semibold">User<select required name="userId" className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-2"><option value="">Select user</option>{users.map((user) => <option value={user.id} key={user.id}>{user.name} · {user.email}</option>)}</select></label><label className="text-sm font-semibold">Reason<input name="reason" className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-2" /></label><button className="mt-6 min-h-11 rounded-xl border border-royalBlue px-4 font-semibold text-royalBlue">Assign package</button></form>
    <section className="mt-8"><h2 className="text-xl font-semibold">Active scope grants</h2><div className="mt-3 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b bg-slate-50"><th className="p-3">User</th><th className="p-3">Scope</th><th className="p-3">Permission</th><th className="p-3">Expiry</th><th className="p-3" /></tr></thead><tbody>{grants.map((grant) => <tr key={grant.id} className="border-b last:border-0"><td className="p-3"><Link className="font-semibold text-royalBlue" href={`/admin/access-control/users/${grant.userId}`}>{grant.user.name}</Link><span className="block text-xs text-slate-500">{grant.user.email}</span></td><td className="p-3">{grant.knowledgeScope.nameEn}</td><td className="p-3">{grant.effect} · {grant.permission}</td><td className="p-3">{grant.expiresAt?.toLocaleDateString() ?? 'No expiry'}</td><td className="p-3"><form action={revokeKnowledgeScopeGrantAction}><input type="hidden" name="grantId" value={grant.id} /><button className="font-semibold text-red-700">Revoke</button></form></td></tr>)}</tbody></table></div></section>
    <section className="mt-8"><h2 className="text-xl font-semibold">Recent audit history</h2><ul className="mt-3 space-y-2">{audit.map((entry) => <li key={entry.id} className="rounded-xl border border-slate-200 bg-white p-3 text-sm"><span className="font-semibold">{entry.action.replaceAll('_', ' ')}</span> · {entry.actor?.name ?? 'System'} · {entry.createdAt.toLocaleString()}</li>)}</ul></section>
  </>;
}
