import { journeyContentSchema, type JourneyContent } from '@/server/cms/journey-content-schema';

export type JourneyEditorNodePath = { moduleIndex?: number; sectionIndex?: number; blockIndex?: number };
export type JourneyMutationResult = { ok: true; content: JourneyContent; selectedPath: JourneyEditorNodePath } | { ok: false; content: JourneyContent; selectedPath: JourneyEditorNodePath; reason: 'INVALID_PATH' | 'BOUNDARY' };
type Direction = 'up' | 'down';
type JsonObject = Record<string, unknown>;
type SupportedBlockType = 'RICH_TEXT' | 'TABLE' | 'DIAGRAM' | 'IMAGE' | 'API_REFERENCE' | 'CODE' | 'DOWNLOAD' | 'CHECKLIST' | 'REFERENCE' | 'CALLOUT';

const clone = <T>(value: T): T => structuredClone(value);
const fail = (content: JourneyContent, selectedPath: JourneyEditorNodePath, reason: 'INVALID_PATH' | 'BOUNDARY'): JourneyMutationResult => ({ ok: false, content, selectedPath, reason });
const success = (content: JourneyContent, selectedPath: JourneyEditorNodePath): JourneyMutationResult => ({ ok: true, content: journeyContentSchema.parse(content), selectedPath });
const modules = (content: JourneyContent) => content.modules ?? [];
const keyFor = (items: Array<{ key?: string }>, base: string) => { const keys = new Set(items.map((item) => item.key)); if (!keys.has(base)) return base; let index = 2; while (keys.has(`${base}-${index}`)) index += 1; return `${base}-${index}`; };
const pathFor = (moduleIndex: number, sectionIndex?: number, blockIndex?: number): JourneyEditorNodePath => ({ moduleIndex, ...(sectionIndex === undefined ? {} : { sectionIndex }), ...(blockIndex === undefined ? {} : { blockIndex }) });

export function updateJourneyModuleTitle(content: JourneyContent, moduleIndex: number, title: string): JourneyMutationResult { if (!modules(content)[moduleIndex]) return fail(content, pathFor(moduleIndex), 'INVALID_PATH'); const next = clone(content); next.modules![moduleIndex].title = title; return success(next, pathFor(moduleIndex)); }
export function addJourneyModule(content: JourneyContent, position = modules(content).length): JourneyMutationResult { const next = clone(content); const index = Math.max(0, Math.min(position, modules(next).length)); const key = keyFor(modules(next), 'new-module'); next.modules = [...modules(next).slice(0, index), { key, title: 'New Module', sections: [] }, ...modules(next).slice(index)]; return success(next, pathFor(index)); }
export function moveJourneyModule(content: JourneyContent, moduleIndex: number, direction: Direction): JourneyMutationResult { const list = modules(content); const target = moduleIndex + (direction === 'up' ? -1 : 1); if (!list[moduleIndex]) return fail(content, pathFor(moduleIndex), 'INVALID_PATH'); if (target < 0 || target >= list.length) return fail(content, pathFor(moduleIndex), 'BOUNDARY'); const next = clone(content); [next.modules![moduleIndex], next.modules![target]] = [next.modules![target], next.modules![moduleIndex]]; return success(next, pathFor(target)); }
export function removeJourneyModule(content: JourneyContent, moduleIndex: number): JourneyMutationResult { const list = modules(content); if (!list[moduleIndex]) return fail(content, pathFor(moduleIndex), 'INVALID_PATH'); const next = clone(content); next.modules!.splice(moduleIndex, 1); return success(next, next.modules?.length ? pathFor(Math.min(moduleIndex, next.modules.length - 1)) : {}); }

export function updateJourneySectionTitle(content: JourneyContent, moduleIndex: number, sectionIndex: number, title: string): JourneyMutationResult { const section = modules(content)[moduleIndex]?.sections[sectionIndex]; if (!section) return fail(content, pathFor(moduleIndex, sectionIndex), 'INVALID_PATH'); const next = clone(content); next.modules![moduleIndex].sections[sectionIndex].title = title; return success(next, pathFor(moduleIndex, sectionIndex)); }
export function addJourneySection(content: JourneyContent, moduleIndex: number, position?: number): JourneyMutationResult { const targetModule = modules(content)[moduleIndex]; if (!targetModule) return fail(content, pathFor(moduleIndex), 'INVALID_PATH'); const next = clone(content); const index = Math.max(0, Math.min(position ?? targetModule.sections.length, targetModule.sections.length)); const key = keyFor(targetModule.sections, 'new-section'); next.modules![moduleIndex].sections.splice(index, 0, { key, title: 'New Section', blocks: [] }); return success(next, pathFor(moduleIndex, index)); }
export function moveJourneySection(content: JourneyContent, moduleIndex: number, sectionIndex: number, direction: Direction): JourneyMutationResult { const list = modules(content)[moduleIndex]?.sections; const target = sectionIndex + (direction === 'up' ? -1 : 1); if (!list) return fail(content, pathFor(moduleIndex, sectionIndex), 'INVALID_PATH'); if (!list[sectionIndex]) return fail(content, pathFor(moduleIndex, sectionIndex), 'INVALID_PATH'); if (target < 0 || target >= list.length) return fail(content, pathFor(moduleIndex, sectionIndex), 'BOUNDARY'); const next = clone(content); [next.modules![moduleIndex].sections[sectionIndex], next.modules![moduleIndex].sections[target]] = [next.modules![moduleIndex].sections[target], next.modules![moduleIndex].sections[sectionIndex]]; return success(next, pathFor(moduleIndex, target)); }
export function removeJourneySection(content: JourneyContent, moduleIndex: number, sectionIndex: number): JourneyMutationResult { const list = modules(content)[moduleIndex]?.sections; if (!list?.[sectionIndex]) return fail(content, pathFor(moduleIndex, sectionIndex), 'INVALID_PATH'); const next = clone(content); next.modules![moduleIndex].sections.splice(sectionIndex, 1); return success(next, next.modules![moduleIndex].sections.length ? pathFor(moduleIndex, Math.min(sectionIndex, next.modules![moduleIndex].sections.length - 1)) : pathFor(moduleIndex)); }

function getBlock(content: JourneyContent, path: JourneyEditorNodePath) { return path.moduleIndex === undefined || path.sectionIndex === undefined || path.blockIndex === undefined ? undefined : modules(content)[path.moduleIndex]?.sections[path.sectionIndex]?.blocks[path.blockIndex]; }
export function addJourneyBlock(content: JourneyContent, moduleIndex: number, sectionIndex: number, position?: number): JourneyMutationResult { const section = modules(content)[moduleIndex]?.sections[sectionIndex]; if (!section) return fail(content, pathFor(moduleIndex, sectionIndex), 'INVALID_PATH'); const next = clone(content); const index = Math.max(0, Math.min(position ?? section.blocks.length, section.blocks.length)); next.modules![moduleIndex].sections[sectionIndex].blocks.splice(index, 0, { blockType: 'RICH_TEXT', schemaVersion: 1, payload: { title: 'New Block', text: '' } }); return success(next, pathFor(moduleIndex, sectionIndex, index)); }
export function duplicateJourneyBlock(content: JourneyContent, path: JourneyEditorNodePath): JourneyMutationResult { const block = getBlock(content, path); if (!block) return fail(content, path, 'INVALID_PATH'); const next = clone(content); next.modules![path.moduleIndex!].sections[path.sectionIndex!].blocks.splice(path.blockIndex! + 1, 0, clone(block)); return success(next, pathFor(path.moduleIndex!, path.sectionIndex!, path.blockIndex! + 1)); }
export function moveJourneyBlock(content: JourneyContent, path: JourneyEditorNodePath, direction: Direction): JourneyMutationResult { const block = getBlock(content, path); const list = path.moduleIndex === undefined || path.sectionIndex === undefined ? undefined : modules(content)[path.moduleIndex]?.sections[path.sectionIndex]?.blocks; const target = (path.blockIndex ?? 0) + (direction === 'up' ? -1 : 1); if (!block || !list) return fail(content, path, 'INVALID_PATH'); if (target < 0 || target >= list.length) return fail(content, path, 'BOUNDARY'); const next = clone(content); const blocks = next.modules![path.moduleIndex!].sections[path.sectionIndex!].blocks; [blocks[path.blockIndex!], blocks[target]] = [blocks[target], blocks[path.blockIndex!]]; return success(next, pathFor(path.moduleIndex!, path.sectionIndex!, target)); }
export function removeJourneyBlock(content: JourneyContent, path: JourneyEditorNodePath): JourneyMutationResult { if (!getBlock(content, path)) return fail(content, path, 'INVALID_PATH'); const next = clone(content); const blocks = next.modules![path.moduleIndex!].sections[path.sectionIndex!].blocks; blocks.splice(path.blockIndex!, 1); return success(next, blocks.length ? pathFor(path.moduleIndex!, path.sectionIndex!, Math.min(path.blockIndex!, blocks.length - 1)) : pathFor(path.moduleIndex!, path.sectionIndex!)); }
export function updateJourneyBlockType(content: JourneyContent, path: JourneyEditorNodePath, blockType: SupportedBlockType): JourneyMutationResult { const block = getBlock(content, path); if (!block) return fail(content, path, 'INVALID_PATH'); const next = clone(content); const target = next.modules![path.moduleIndex!].sections[path.sectionIndex!].blocks[path.blockIndex!]; target.blockType = blockType; target.payload = { title: typeof target.payload.title === 'string' ? target.payload.title : 'New Block' }; return success(next, path); }
export function updateJourneyBlockPayload(content: JourneyContent, path: JourneyEditorNodePath, payload: JsonObject): JourneyMutationResult { const block = getBlock(content, path); if (!block) return fail(content, path, 'INVALID_PATH'); const next = clone(content); next.modules![path.moduleIndex!].sections[path.sectionIndex!].blocks[path.blockIndex!].payload = clone(payload); return success(next, path); }
