import { db } from '@/lib/db';
import { getServerEnvironment } from '@/server/env';
import type { GovernedContentActor } from '@/server/cms/governed-content-lifecycle';
import { assertContentReadBack, assertGovernedDraftEditable, assertGovernedDraftSubmittable, assertGovernedRevisionPublishable, assertGovernedRevisionReviewable, governedAuditMetadata } from '@/server/cms/governed-content-lifecycle';
import { customerSegmentContentSchema, customerSegmentSlugSchema, parseCustomerSegmentContent, type CustomerSegmentContent } from './customer-segment-domain';

const label = 'Customer Segment';
async function assertAssignments(contentItemId: string, content: CustomerSegmentContent) {
  const journeys = await db.contentItem.findMany({ where: { type: 'BANKING_JOURNEY', slug: { in: content.journeys }, isArchived: false, publishedRevisionId: { not: null } }, select: { slug: true } });
  if (journeys.length !== content.journeys.length) throw new Error('Customer Segment references an unavailable Journey.');
  const others = await db.contentItem.findMany({ where: { type: 'CUSTOMER_SEGMENT', id: { not: contentItemId }, isArchived: false, publishedRevisionId: { not: null } }, select: { publishedRevision: { select: { contentJson: true } } } });
  const assigned = new Set(others.flatMap((item) => parseCustomerSegmentContent(item.publishedRevision?.contentJson ?? '')?.journeys ?? []));
  if (content.journeys.some((slug) => assigned.has(slug))) throw new Error('A Journey may belong to only one published Customer Segment.');
}
export async function createCustomerSegment(slugValue: string, actor: GovernedContentActor) {
  const slug = customerSegmentSlugSchema.parse(slugValue); const existing = await db.contentItem.findUnique({ where: { type_slug: { type: 'CUSTOMER_SEGMENT', slug } } }); if (existing) return existing;
  const fallback = (await import('@/server/journey-segments')).findJourneySegment(slug)!; const content = customerSegmentContentSchema.parse({ schemaVersion: 1, en: fallback.en, vi: fallback.vi, journeys: fallback.journeys }); const contentJson = JSON.stringify(content);
  return db.$transaction(async (tx) => { const item = await tx.contentItem.create({ data: { type: 'CUSTOMER_SEGMENT', slug, stableKey: `customer-segment:${slug}`, ownerId: actor.id, previewJson: JSON.stringify({ title: content.en.title, summary: content.en.description }) } }); const revision = await tx.contentRevision.create({ data: { contentItemId: item.id, version: 1, contentJson, authorId: actor.id } }); await tx.auditLog.create({ data: { actorId: actor.id, action: 'CUSTOMER_SEGMENT_CREATED', entityType: 'ContentItem', entityId: item.id, metadataJson: governedAuditMetadata(getServerEnvironment().APP_ENV, { slug, revisionId: revision.id }) } }); return item; });
}
export async function createCustomerSegmentDraft(contentItemId: string, actor: GovernedContentActor) {
  const item = await db.contentItem.findFirst({ where: { id: contentItemId, type: 'CUSTOMER_SEGMENT', isArchived: false }, include: { publishedRevision: true, revisions: { where: { status: { in: ['DRAFT', 'CHANGES_REQUESTED'] } }, take: 1 }, _count: { select: { revisions: true } } } });
  if (!item?.publishedRevision) throw new Error('A published Customer Segment is required to create a new draft.');
  if (item.revisions[0]) return item.revisions[0];
  return db.$transaction(async (tx) => { const revision = await tx.contentRevision.create({ data: { contentItemId, version: item._count.revisions + 1, contentJson: item.publishedRevision!.contentJson, authorId: actor.id } }); await tx.auditLog.create({ data: { actorId: actor.id, action: 'CUSTOMER_SEGMENT_DRAFT_CREATED', entityType: 'ContentRevision', entityId: revision.id, metadataJson: governedAuditMetadata(getServerEnvironment().APP_ENV, { contentItemId, sourceRevisionId: item.publishedRevisionId }) } }); return revision; });
}
export async function saveCustomerSegment(contentItemId: string, revisionId: string, value: unknown, actor: GovernedContentActor) { const content = customerSegmentContentSchema.parse(value); await assertAssignments(contentItemId, content); const json = JSON.stringify(content); const revision = await db.contentRevision.findFirst({ where: { id: revisionId, contentItemId, contentItem: { type: 'CUSTOMER_SEGMENT' } } }); if (!revision) throw new Error('Customer Segment revision not found.'); assertGovernedDraftEditable({ ...revision, actorId: actor.id, role: actor.role }, label); await db.$transaction(async (tx) => { const updated = await tx.contentRevision.update({ where: { id: revision.id }, data: { contentJson: json } }); assertContentReadBack(json, updated.contentJson, 'Customer Segment save'); await tx.contentItem.update({ where: { id: contentItemId }, data: { previewJson: JSON.stringify({ title: content.en.title, summary: content.en.description }) } }); await tx.auditLog.create({ data: { actorId: actor.id, action: 'CUSTOMER_SEGMENT_DRAFT_UPDATED', entityType: 'ContentRevision', entityId: revision.id, metadataJson: governedAuditMetadata(getServerEnvironment().APP_ENV, { contentItemId }) } }); }); }
export async function submitCustomerSegment(contentItemId: string, revisionId: string, actor: GovernedContentActor) { const revision = await db.contentRevision.findFirst({ where: { id: revisionId, contentItemId, contentItem: { type: 'CUSTOMER_SEGMENT' } } }); if (!revision) throw new Error('Customer Segment revision not found.'); assertGovernedDraftSubmittable({ ...revision, actorId: actor.id, role: actor.role }, label, true); await db.contentRevision.update({ where: { id: revisionId }, data: { status: 'IN_REVIEW', submittedAt: new Date(), reviewNote: null } }); await db.auditLog.create({ data: { actorId: actor.id, action: 'CUSTOMER_SEGMENT_SUBMITTED', entityType: 'ContentRevision', entityId: revisionId } }); }
export async function reviewCustomerSegment(contentItemId: string, revisionId: string, decision: 'changes' | 'reject', note: string, actor: GovernedContentActor) { const revision = await db.contentRevision.findFirst({ where: { id: revisionId, contentItemId, contentItem: { type: 'CUSTOMER_SEGMENT' } } }); if (!revision) throw new Error('Customer Segment revision not found.'); assertGovernedRevisionReviewable({ ...revision, actorId: actor.id, role: actor.role }, label); await db.contentRevision.update({ where: { id: revisionId }, data: { status: decision === 'changes' ? 'CHANGES_REQUESTED' : 'REJECTED', reviewerId: actor.id, reviewedAt: new Date(), reviewNote: note } }); }
export async function publishCustomerSegment(contentItemId: string, revisionId: string, actor: GovernedContentActor) { const revision = await db.contentRevision.findFirst({ where: { id: revisionId, contentItemId, contentItem: { type: 'CUSTOMER_SEGMENT' } } }); if (!revision) throw new Error('Customer Segment revision not found.'); assertGovernedRevisionPublishable({ ...revision, actorId: actor.id, role: actor.role }, label); const content = parseCustomerSegmentContent(revision.contentJson); if (!content) throw new Error('Customer Segment content is invalid.'); await assertAssignments(contentItemId, content); await db.$transaction(async (tx) => { const now = new Date(); const published = await tx.contentRevision.update({ where: { id: revisionId }, data: { status: 'PUBLISHED', reviewerId: actor.id, reviewedAt: now, publishedAt: now } }); assertContentReadBack(revision.contentJson, published.contentJson, 'Customer Segment publish'); await tx.contentItem.update({ where: { id: contentItemId }, data: { publishedRevisionId: revisionId } }); await tx.auditLog.create({ data: { actorId: actor.id, action: 'CUSTOMER_SEGMENT_PUBLISHED', entityType: 'ContentItem', entityId: contentItemId } }); }); }
