import { notFound } from 'next/navigation';
import { Footer } from '@/components/layout/Footer'; import { Navbar } from '@/components/layout/Navbar'; import { Container } from '@/components/ui/Container'; import { CaseStudyVisual } from '@/components/case-studies/CaseStudyVisual';
import { ArticleLayout, Callout, ContentHero, ContentSection, JsonLd, List, PreviousNext, ProcessFlow, RelatedContent } from '@/components/content/Editorial';
import { baPracticeContent, bankingJourneyContent, caseStudyContent } from '@/data/content';
import { KnowledgeActions } from '@/components/member/KnowledgeActions';
import { requirePremiumAccess } from '@/lib/membership';
import {getCurrentLocale} from '@/i18n/server'; import {TranslationUnavailable} from '@/components/content/TranslationUnavailable';
export default async function CaseDetail({ params }: { params: Promise<{ slug: string }> }) {
 await requirePremiumAccess('/case-studies');
 if(await getCurrentLocale()==='vi')return <TranslationUnavailable englishPath={`/case-studies/${(await params).slug}`}/>;
 const { slug } = await params; const x = caseStudyContent.find((i) => i.slug === slug); if (!x) notFound(); const i = caseStudyContent.indexOf(x), prev = caseStudyContent[i - 1], next = caseStudyContent[i + 1];
 const journeys = x.relatedJourneySlugs.flatMap((slug) => { const v = bankingJourneyContent.find((a) => a.slug === slug); return v ? [{ href: `/banking-journeys/${v.slug}`, label: v.title, context: 'Banking Journey' }] : []; });
 const practices = x.relatedPracticeSlugs.flatMap((slug) => { const v = baPracticeContent.find((a) => a.slug === slug); return v ? [{ href: `/ba-practice/${v.slug}`, label: v.title, context: 'BA Practice' }] : []; });
 const related = x.relatedCaseStudySlugs.flatMap((slug) => { const v = caseStudyContent.find((a) => a.slug === slug); return v && v.slug !== x.slug ? [{ href: `/case-studies/${v.slug}`, label: v.title, context: 'Case Study' }] : []; });
 const toc = [{ id: 'challenge', label: 'Challenge and context' }, { id: 'current', label: 'Current state' }, { id: 'approach', label: 'Analysis approach' }, { id: 'findings', label: 'Findings and gaps' }, { id: 'recommendation', label: 'Recommendations' }, { id: 'lessons', label: 'Lessons and questions' }, { id: 'related', label: 'Related knowledge' }];
 return <><Navbar /><main><JsonLd data={{ '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: x.title, description: x.summary, articleSection: x.contentType }, { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: '/' }, { '@type': 'ListItem', position: 2, name: 'Case Studies', item: '/case-studies' }, { '@type': 'ListItem', position: 3, name: x.title }] }] }} /><ContentHero eyebrow={x.contentType} title={x.title} summary={x.summary} parentLabel="Case Studies" parentHref="/case-studies" meta={[x.domain, x.level, x.readingTime]} /><section className="px-4 py-12 sm:px-6 lg:px-8"><Container><KnowledgeActions type="CASE_STUDY" slug={x.slug} /><ArticleLayout toc={toc}>
 <div className="overflow-hidden rounded-2xl"><CaseStudyVisual type={x.visualType} /></div><Callout label="Educational case study">{x.businessContext}</Callout>
 <ContentSection id="challenge" title="Business challenge and context"><p>{x.challenge}</p><h3 className="mt-5 font-semibold text-textPrimary">Stakeholders</h3><List items={x.stakeholders} /></ContentSection>
 <ContentSection id="current" title="Current state and requirements"><div className="grid gap-6 sm:grid-cols-2"><div><h3 className="font-semibold text-textPrimary">Current state</h3><List items={x.currentState} /></div><div><h3 className="font-semibold text-textPrimary">Business requirements</h3><List items={x.requirements} /></div></div></ContentSection>
 <ContentSection id="approach" title="Analysis approach"><ProcessFlow steps={x.analysisApproach} /></ContentSection>
 <ContentSection id="findings" title="Findings and gaps"><List items={x.findings} /><div className="mt-6 space-y-3">{x.gaps.map((gap) => <div key={gap.title} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-goldAccent">Severity: {gap.severity ?? 'Not rated'}</p><h3 className="mt-1 font-semibold text-textPrimary">{gap.title}</h3><p className="mt-1">{gap.description}</p></div>)}</div></ContentSection>
 <ContentSection id="recommendation" title="Recommendations and expected artifacts"><h3 className="font-semibold text-textPrimary">Recommendations</h3><List items={x.recommendation} /><h3 className="mt-6 font-semibold text-textPrimary">Expected BA artifacts</h3><List items={x.expectedArtifacts} /></ContentSection>
 <ContentSection id="lessons" title="Lessons learned and discussion questions"><div className="grid gap-6 sm:grid-cols-2"><div><h3 className="font-semibold text-textPrimary">Lessons learned</h3><List items={x.lessonsLearned} /></div><div><h3 className="font-semibold text-textPrimary">Discussion questions</h3><List items={x.discussionQuestions} /></div></div></ContentSection>
 <div id="related" className="space-y-8"><RelatedContent title="Related journeys" links={journeys} /><RelatedContent title="Related BA practices" links={practices} /><RelatedContent title="Related cases" links={related} /></div>
 <PreviousNext previous={prev ? { href: `/case-studies/${prev.slug}`, label: prev.title, context: '' } : undefined} next={next ? { href: `/case-studies/${next.slug}`, label: next.title, context: '' } : undefined} backHref="/case-studies" backLabel="Knowledge library" />
 </ArticleLayout></Container></section></main><Footer /></>;
}
