'use client';
import { useMemo, useState, useTransition } from 'react';
import { validateBaDocumentJson, type BaDocumentValidationResult } from '@/server/ba-document/ba-document-validation';
import { saveBaDocumentAction } from './actions';

function ValidationResults({result}:{result:BaDocumentValidationResult}){
  if(result.status==='VALID')return <div role="status" className="rounded-xl border border-green-300 bg-green-50 p-4 text-green-900"><strong>VALID</strong> — canonical BaDocumentContentV1 validation passed.</div>;
  const grouped=Object.entries(Object.groupBy(result.issues,(issue)=>issue.path.startsWith('modules.')?'Blocks':issue.path.startsWith('artifacts.')?'Artifacts':'Document'));
  return <section role="alert" className="rounded-xl border border-red-300 bg-red-50 p-4 text-red-950"><h3 className="font-semibold">Validation failed — {result.issueCount} issues</h3><p className="mt-1 text-sm">Blocks — {result.groups.blocks} · Artifacts — {result.groups.artifacts} · Other — {result.groups.other}</p>{result.nonCanonicalBlockCount?<p className="mt-3 rounded-lg bg-white p-3 font-semibold">{result.nonCanonicalBlockCount} blocks use a non-canonical shape. Expected: id + schemaVersion + blockType + payload.</p>:null}<div className="mt-3 space-y-2">{grouped.map(([label,issues])=><details key={label} className="rounded-lg border border-red-200 bg-white p-3"><summary className="cursor-pointer font-semibold">{label} ({issues?.length??0})</summary><ul className="mt-3 max-h-80 space-y-2 overflow-auto text-sm">{issues?.map((issue,index)=><li key={`${issue.path}-${issue.code}-${index}`} className="border-t pt-2 first:border-0"><code className="break-all text-xs">{issue.path}</code>{issue.blockId||issue.artifactId?<span className="ml-2 font-semibold">{issue.blockId??issue.artifactId}</span>:null}<span className="block">{issue.message}</span></li>)}</ul></details>)}</div></section>;
}

export function BaDocumentEditor({ slug, revisionId, initialJson }: { slug: string; revisionId: string; initialJson: string }) {
  const initial=useMemo(()=>JSON.parse(initialJson) as {metadata:{documentCode:string;title:string;summary:string};modules:unknown[];artifacts:Record<string,unknown[]>},[initialJson]);
  const [json,setJson]=useState(initialJson),[code,setCode]=useState(initial.metadata.documentCode),[title,setTitle]=useState(initial.metadata.title),[summary,setSummary]=useState(initial.metadata.summary),[result,setResult]=useState<BaDocumentValidationResult>(),[saved,setSaved]=useState(false);const[pending,startTransition]=useTransition();
  function currentJson(){try{const current=JSON.parse(json);current.metadata={...current.metadata,documentCode:code,title,summary};const next=JSON.stringify(current,null,2);setJson(next);return next}catch{return json}}
  function validate(){setSaved(false);setResult(validateBaDocumentJson(currentJson()));}
  function save(){const current=currentJson();const local=validateBaDocumentJson(current);setResult(local);setSaved(false);if(local.status!=='VALID')return;startTransition(async()=>{const data=new FormData();data.set('slug',slug);data.set('revisionId',revisionId);data.set('contentJson',current);const response=await saveBaDocumentAction(data);if(response.ok){setSaved(true);setResult(validateBaDocumentJson(current));}else setResult(response.validation);});}
  return <div className="space-y-5 rounded-2xl border bg-white p-5"><div className="grid gap-4 md:grid-cols-2"><label className="font-semibold">Document code<input value={code} onChange={e=>setCode(e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border px-3 font-normal"/></label><label className="font-semibold">Title<input value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border px-3 font-normal"/></label></div><label className="block font-semibold">Summary<textarea value={summary} onChange={e=>setSummary(e.target.value)} rows={3} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label><details className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950"><summary className="cursor-pointer font-semibold">Canonical Advanced JSON guidance</summary><div className="mt-3 space-y-2"><p>Schema: <code>BaDocumentContentV1</code></p><p>Top level: <code>schemaVersion, documentType, metadata, modules, artifacts</code></p><p>Canonical block: <code>id, schemaVersion, blockType, payload</code></p><p>Stable artifact IDs: <code>ONB-BR-001, ONB-FR-001, ONB-RULE-001, ONB-VAL-001, ONB-PROC-001, ONB-DATA-001, ONB-MAP-001, ONB-AC-001, ONB-UAT-001, ONB-DEC-001</code></p><p>Legacy shapes such as <code>type: paragraph</code>, <code>bulletList</code>, <code>table</code>, or <code>artifactRefs</code> are not accepted or automatically converted.</p></div></details><p className="rounded-xl bg-slate-50 p-3 text-sm">{initial.modules.length} modules · {Object.values(initial.artifacts).reduce((sum,items)=>sum+items.length,0)} artifacts. Missing business information is never generated automatically.</p><label className="block font-semibold">Structured modules, blocks and artifact collections<textarea name="contentJson" value={json} onChange={e=>{setJson(e.target.value);setResult(undefined);setSaved(false)}} rows={28} className="mt-2 w-full rounded-xl border p-3 font-mono text-xs font-normal"/></label>{result?<ValidationResults result={result}/>:null}{saved?<p role="status" className="rounded-xl bg-green-50 p-3 font-semibold text-green-900">Saved and verified against database read-back.</p>:null}<div className="flex flex-wrap gap-3"><button type="button" onClick={validate} className="min-h-11 rounded-xl border border-royalBlue px-5 font-semibold text-royalBlue">Validate JSON</button><button type="button" disabled={pending} onClick={save} className="min-h-11 rounded-xl bg-royalBlue px-5 font-semibold text-white disabled:opacity-60">{pending?'Saving…':'Save and verify'}</button></div></div>;
}
