'use client';
import { useMemo, useState } from 'react';
import { saveBaDocumentAction } from './actions';

export function BaDocumentEditor({ slug, revisionId, initialJson }: { slug: string; revisionId: string; initialJson: string }) {
  const initial = useMemo(() => JSON.parse(initialJson) as { metadata: { documentCode:string; title:string; summary:string }; modules: unknown[]; artifacts: Record<string,unknown[]> }, [initialJson]);
  const [json,setJson]=useState(initialJson); const [code,setCode]=useState(initial.metadata.documentCode); const [title,setTitle]=useState(initial.metadata.title); const [summary,setSummary]=useState(initial.metadata.summary); const [error,setError]=useState('');
  function synchronize() { try { const current=JSON.parse(json); current.metadata={...current.metadata,documentCode:code,title,summary}; const next=JSON.stringify(current,null,2); setJson(next); setError(''); return next; } catch { setError('Current JSON is invalid. Correct it before saving.'); return null; } }
  return <form action={saveBaDocumentAction} onSubmit={(event)=>{const next=synchronize();if(!next){event.preventDefault();return;}const field=event.currentTarget.elements.namedItem('contentJson') as HTMLTextAreaElement;field.value=next;}} className="space-y-5 rounded-2xl border bg-white p-5"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="revisionId" value={revisionId}/><div className="grid gap-4 md:grid-cols-2"><label className="font-semibold">Document code<input value={code} onChange={(e)=>setCode(e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border px-3 font-normal"/></label><label className="font-semibold">Title<input value={title} onChange={(e)=>setTitle(e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border px-3 font-normal"/></label></div><label className="block font-semibold">Summary<textarea value={summary} onChange={(e)=>setSummary(e.target.value)} rows={3} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label><div className="rounded-xl bg-blue-50 p-4 text-sm text-blue-900">Structured authoring foundation: {initial.modules.length} modules · {Object.values(initial.artifacts).reduce((sum,items)=>sum+items.length,0)} artifacts. Stable IDs and references are validated on save.</div><label className="block font-semibold">Structured modules, blocks and artifact collections<textarea name="contentJson" value={json} onChange={(e)=>setJson(e.target.value)} rows={28} className="mt-2 w-full rounded-xl border p-3 font-mono text-xs font-normal"/></label>{error?<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-800">{error}</p>:null}<button className="min-h-11 rounded-xl bg-royalBlue px-5 font-semibold text-white">Save and verify</button></form>;
}
