import Link from 'next/link';
import { ArrowRight, BookOpen, BriefcaseBusiness, Building2, FileSearch, Search } from 'lucide-react';
import type { ContentType } from '@prisma/client';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
import { ContentRepository, type MemberHomeData } from '@/lib/repository';
import { getCurrentLocale } from '@/i18n/server';
import { formatDate } from '@/i18n/format';

const routes: Record<ContentType,string>={BANKING_JOURNEY:'banking-journeys',BA_PRACTICE:'ba-practice',CASE_STUDY:'case-studies',CAREER_LEVEL:'career-roadmap'};
const icons={BANKING_JOURNEY:Building2,BA_PRACTICE:FileSearch,CASE_STUDY:BookOpen,CAREER_LEVEL:BriefcaseBusiness} as const;
const labels={
  en:{eyebrow:'BANKING BA KNOWLEDGE HUB',title:'What do you want to explore?',supporting:'Explore banking journeys, business rules, processes, and practical BA knowledge across the platform.',search:'Search journeys, processes, business rules, validations...',suggestions:'Try:',explore:'Explore knowledge',exploreCopy:'Navigate directly to the knowledge available in your membership.',domains:'Banking domains',domainsCopy:'Explore the banking areas included in your current knowledge access.',recent:'Recently updated',recentCopy:'The latest published knowledge available to you.',view:'View knowledge',types:{BANKING_JOURNEY:'Banking Journeys',BA_PRACTICE:'BA Practice',CASE_STUDY:'Case Studies',CAREER_LEVEL:'Career Roadmap'}},
  vi:{eyebrow:'BANKING BA KNOWLEDGE HUB',title:'Bạn muốn khám phá nội dung nào?',supporting:'Khám phá hành trình ngân hàng, quy tắc nghiệp vụ, quy trình và kiến thức BA thực tiễn trên nền tảng.',search:'Tìm hành trình, quy trình, quy tắc nghiệp vụ...',suggestions:'Gợi ý:',explore:'Khám phá kiến thức',exploreCopy:'Đi tới các nhóm kiến thức hiện có trong quyền truy cập của bạn.',domains:'Lĩnh vực ngân hàng',domainsCopy:'Khám phá các lĩnh vực thuộc phạm vi kiến thức hiện tại của bạn.',recent:'Mới cập nhật',recentCopy:'Nội dung tiếng Việt đã xuất bản gần đây.',view:'Xem nội dung',types:{BANKING_JOURNEY:'Hành trình ngân hàng',BA_PRACTICE:'Phương pháp BA',CASE_STUDY:'Case Study',CAREER_LEVEL:'Lộ trình nghề nghiệp'}},
} as const;

export async function MemberHome({userId,userName}:{userId:string;userName:string}){const locale=await getCurrentLocale();const data=await ContentRepository.getMemberHomeData(userId,locale);return <MemberHomeView locale={locale} userName={userName} data={data}/>}

export function MemberHomeView({locale,userName,data}:{locale:'en'|'vi';userName:string;data:MemberHomeData}){const copy=labels[locale],suggestions=data.recentlyUpdated.slice(0,4).map(item=>item.title);return <><Navbar/><main>
<section className="bg-navy px-4 py-14 text-white sm:px-6 sm:py-20 lg:py-24"><div className="mx-auto max-w-7xl"><p className="text-sm font-semibold tracking-wide text-goldLight">{copy.eyebrow}</p><p className="mt-4 text-sm text-slate-300">{locale==='vi'?`Xin chào, ${userName}`:`Welcome, ${userName}`}</p><h1 className="mt-3 max-w-4xl text-4xl font-semibold tracking-tight sm:text-5xl lg:text-6xl">{copy.title}</h1><p className="mt-5 max-w-3xl text-base leading-7 text-slate-300 sm:text-lg">{copy.supporting}</p><form action={`/${locale}/search`} className="mt-8 flex max-w-4xl flex-col gap-3 rounded-2xl bg-white p-3 shadow-soft sm:flex-row sm:items-center"><Search aria-hidden="true" className="ml-2 hidden h-6 w-6 text-slate-500 sm:block"/><label htmlFor="member-home-search" className="sr-only">{copy.search}</label><input id="member-home-search" name="q" type="search" placeholder={copy.search} className="min-h-12 min-w-0 flex-1 rounded-xl px-3 text-textPrimary outline-none"/><button className="min-h-12 rounded-xl bg-royalBlue px-6 font-semibold text-white">{locale==='vi'?'Tìm kiếm':'Search'}</button></form>{suggestions.length?<p className="mt-3 text-xs text-slate-400">{copy.suggestions} {suggestions.join(' · ')}</p>:null}</div></section>
<section className="px-4 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-semibold text-navy">{copy.explore}</h2><p className="mt-3 text-textSecondary">{copy.exploreCopy}</p>{data.permittedTypes.length?<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{data.permittedTypes.map(type=>{const Icon=icons[type];return <Link key={type} href={`/${locale}/${routes[type]}`} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm hover:border-royalBlue/40"><Icon className="h-6 w-6 text-royalBlue"/><h3 className="mt-8 text-xl font-semibold text-navy">{copy.types[type]}</h3><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-royalBlue">{copy.view}<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1"/></span></Link>})}</div>:<div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-8"><p className="font-semibold">{locale==='vi'?'Chưa có phạm vi kiến thức được cấp.':'No knowledge scope is currently assigned.'}</p></div>}</div></section>
{data.domains.length?<section className="bg-white px-4 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-semibold text-navy">{copy.domains}</h2><p className="mt-3 text-textSecondary">{copy.domainsCopy}</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.domains.map(domain=><article key={domain.code} className="rounded-2xl bg-bgLight p-6"><p className="text-xs font-semibold tracking-wide text-goldAccent">{domain.code}</p><h3 className="mt-3 text-lg font-semibold">{domain.name}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-textSecondary">{domain.description}</p></article>)}</div></div></section>:null}
{data.recentlyUpdated.length?<section className="px-4 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-semibold text-navy">{copy.recent}</h2><p className="mt-3 text-textSecondary">{copy.recentCopy}</p><div className="mt-8 grid gap-4 md:grid-cols-2">{data.recentlyUpdated.map(item=><Link key={item.id} href={`/${locale}/${routes[item.type]}/${item.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-6 hover:border-royalBlue/40"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs font-semibold text-goldAccent">{copy.types[item.type]}</span><time className="text-xs text-textSecondary" dateTime={item.updatedAt.toISOString()}>{formatDate(item.updatedAt,locale)}</time></div><h3 className="mt-3 text-xl font-semibold text-navy">{item.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-textSecondary">{item.summary}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-royalBlue">{copy.view}<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1"/></span></Link>)}</div></div></section>:null}
</main><Footer mode="member"/></>}
